rem DML statements to create data for FIFA World Cup Football 2014

--------------------------------------------------------
--  File created - Tuesday-July-01-2014   
--------------------------------------------------------
REM INSERTING into WC_FOOTBALL_REGIONS
SET DEFINE OFF;
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (1,'Middle East','AS');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (2,'Africa','AF');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (3,'Far East','AS');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (4,'South America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (5,'North America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (6,'Central America','AM');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (7,'North Western Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (8,'Eastern Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (9,'Southern Europe','EU');
Insert into WC_FOOTBALL_REGIONS (ID,NAME,CONTINENT) values (10,'Pacific','PC');
REM INSERTING into WC_MATCH_RESULTS
SET DEFINE OFF;


--------------------------------------------------------
--  File created - Thursday-July-10-2014   
--------------------------------------------------------
REM INSERTING into WC_MATCH_RESULTS
SET DEFINE OFF;
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,1,7,1,1,8,to_timestamp('28-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'01-;|h',49);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,9,13,2,0,1,to_timestamp('28-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'1-1;',50);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,6,3,2,1,6,to_timestamp('29-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-100;',51);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,14,10,1,1,11,to_timestamp('29-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-01;1100|h',52);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,21,17,1,0,5,to_timestamp('01-07-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-0;',55);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,29,28,2,1,12,to_timestamp('01-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;001|',56);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',9,10,3,0,8,to_timestamp('14-06-2014 10:00:00','DD-MM-YYYY HH24:MI:SS'),'000',5);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',4,1,1,4,4,to_timestamp('23-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'101-11;',33);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',2,3,1,3,11,to_timestamp('23-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-1110;',34);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',6,7,2,0,5,to_timestamp('23-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'00',36);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',8,5,0,3,9,to_timestamp('23-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'111',35);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',11,12,2,1,11,to_timestamp('14-06-2014 22:00:00','DD-MM-YYYY HH24:MI:SS'),'100',6);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',9,11,2,1,4,to_timestamp('19-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'001',21);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',12,10,0,0,3,to_timestamp('19-06-2014 22:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',22);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',1,2,3,1,5,to_timestamp('12-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'10-00;',1);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',3,4,1,0,3,to_timestamp('13-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-0;',2);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',1,3,0,0,6,to_timestamp('17-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',17);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('A',4,2,0,4,2,to_timestamp('18-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'1-111;',18);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',5,6,1,5,12,to_timestamp('13-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'011111',3);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',7,8,3,1,7,to_timestamp('13-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'0010',4);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',5,7,0,2,1,to_timestamp('18-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'11',19);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('B',8,6,2,3,10,to_timestamp('18-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'10011',20);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',29,30,2,1,8,to_timestamp('17-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'100',15);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',31,32,1,1,7,to_timestamp('17-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'111',16);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',29,31,1,0,1,to_timestamp('22-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'111',31);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',32,30,2,4,10,to_timestamp('22-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'111',32);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',32,29,1,0,5,to_timestamp('26-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'111',47);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('H',30,31,1,1,9,to_timestamp('26-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'111',48);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',13,14,1,3,6,to_timestamp('14-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',7);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',15,16,1,2,2,to_timestamp('14-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'101',8);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',13,15,2,1,5,to_timestamp('19-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',23);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',16,14,0,1,11,to_timestamp('20-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',24);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',16,13,0,1,3,to_timestamp('24-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',39);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('D',14,15,0,0,8,to_timestamp('24-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',40);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',17,18,2,1,4,to_timestamp('15-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',9);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',19,20,3,0,10,to_timestamp('15-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'111',10);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',17,19,2,5,12,to_timestamp('20-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'111',25);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',20,18,1,2,9,to_timestamp('20-06-2014 19:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',26);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',20,17,0,3,2,to_timestamp('25-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'111',41);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('E',18,19,0,0,1,to_timestamp('25-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',42);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',21,22,2,1,1,to_timestamp('15-06-2014 19:00:00','DD-MM-YYYY HH24:MI:SS'),'001',11);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',23,24,0,0,9,to_timestamp('16-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',12);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',21,23,1,0,8,to_timestamp('21-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'0',27);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',24,22,1,0,7,to_timestamp('21-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'0',28);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',24,21,2,3,10,to_timestamp('25-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'10101',43);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('F',22,23,3,1,12,to_timestamp('25-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',44);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',25,26,4,0,12,to_timestamp('16-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'0000',13);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',27,28,1,2,3,to_timestamp('16-06-2014 19:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',14);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',25,27,2,2,6,to_timestamp('21-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',29);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',28,26,2,2,2,to_timestamp('22-06-2014 18:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',30);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',28,25,0,1,11,to_timestamp('26-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',45);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('G',26,27,2,1,4,to_timestamp('26-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',46);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',12,9,1,4,8,to_timestamp('24-06-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',37);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values ('C',10,11,2,1,6,to_timestamp('24-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;',38);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,1,9,2,1,6,to_timestamp('04-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'0-01;',57);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,19,25,0,1,1,to_timestamp('04-07-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'1-;',58);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,21,29,1,0,4,to_timestamp('05-07-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'0-;',60);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,6,14,0,0,12,to_timestamp('05-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;|h',59);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,1,25,1,7,8,to_timestamp('08-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'11111-110;',61);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,6,21,0,0,5,to_timestamp('09-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;|a',62);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,19,24,2,0,1,to_timestamp('30-06-2014 13:00:00','DD-MM-YYYY HH24:MI:SS'),'-00;',53);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,25,30,2,1,1,to_timestamp('30-06-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'-;001|',54);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,1,6,0,3,4,to_timestamp('12-07-2014 17:00:00','DD-MM-YYYY HH24:MI:SS'),'11-1;',63);
Insert into WC_MATCH_RESULTS (GROUP1,HOME_TEAM_ID,AWAY_TEAM_ID,HOME_GOALS,AWAY_GOALS,SDM_ID,LOCAL_START_TIME,SCORING_PROCESS,ID) values (null,25,21,1,0,1,to_timestamp('13-07-2014 16:00:00','DD-MM-YYYY HH24:MI:SS'),'-;0|',64);


REM INSERTING into WC_MATCH_TAGS
SET DEFINE OFF;
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (1,1);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (1,3);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (3,3);
Insert into WC_MATCH_TAGS (TAG_ID,MATCH_ID) values (3,20);
REM INSERTING into WC_STADIUMS
SET DEFINE OFF;
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (1,'Est?dio do Maracan?','Rio de Janeiro',23,43);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (4,'Est?dio Nacional Man? Garrincha','Brasilia',15,48);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (5,'Arena de S?o Paulo','Sao Paulo',23,46);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (6,'Est?dio Castel?o','Fortaleza',3,38);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (8,'Est?dio Mineir?o','Belo Horizonte',20,44);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (10,'Est?dio Beira-Rio','Porto Alegre',30,51);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (2,'Arena da Amaz?nia','Manaus',3,60);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (12,'Arena Fonte Nova','Salvador',13,38);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (7,'Arena Pantanal','Cuiaba',15,56);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (3,'Arena das Dunas','Natal',5,35);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (9,'Arena da Baixada','Curitiba',25,49);
Insert into WC_STADIUMS (ID,NAME,CITY,LATTITUDE,LONGITUDE) values (11,'Arena Pernambuco','Recife',8,35);
REM INSERTING into WC_TAGS
SET DEFINE OFF;
Insert into WC_TAGS (ID,TAG) values (1,'referential integrity');
Insert into WC_TAGS (ID,TAG) values (2,'hattrick');
Insert into WC_TAGS (ID,TAG) values (3,'super goal');
Insert into WC_TAGS (ID,TAG) values (4,'extreme heat');
Insert into WC_TAGS (ID,TAG) values (5,'extra time');
Insert into WC_TAGS (ID,TAG) values (6,'penalty shootout');
Insert into WC_TAGS (ID,TAG) values (7,'red card');
Insert into WC_TAGS (ID,TAG) values (8,'injury');

REM INSERTING into WC_TEAMS
SET DEFINE OFF;
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (1,'BRA','A',1,3,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (2,'CRO','A',2,18,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (3,'MEX','A',3,20,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (4,'CMR','A',4,56,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (5,'ESP','B',1,1,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (6,'NLD','B',2,15,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (7,'CHL','B',3,14,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (8,'AUS','B',4,62,10);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (9,'COL','C',1,8,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (10,'GRC','C',2,12,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (11,'CIV','C',3,23,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (12,'JPN','C',4,46,3);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (13,'URU','D',1,7,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (14,'CRC','D',2,28,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (15,'ENG','D',3,10,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (16,'ITA','D',4,9,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (17,'SUI','E',1,6,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (18,'ECU','E',2,26,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (19,'FRA','E',3,17,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (20,'HON','E',4,33,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (21,'ARG','F',1,5,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (22,'BIH','F',2,21,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (23,'IRI','F',3,43,1);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (24,'NGR','F',4,44,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (25,'GER','G',1,2,4);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (26,'POR','G',2,4,9);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (27,'GHA','G',3,37,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (28,'USA','G',4,13,5);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (29,'BEL','H',1,11,7);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (30,'ALG','H',2,22,2);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (31,'RUS','H',3,19,8);
Insert into WC_TEAMS (ID,COUNTRY,GROUP1,SEQ_IN_GROUP,FIFA_RANK,RGN_ID) values (32,'KOR','H',4,57,3);

